In [14]:
import pandas as pd

titanic = pd.read_csv("train.csv")

titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [15]:
titanic = titanic.loc[:,["Pclass", "Sex", "Age", "Survived"]]
titanic

Pclass     Sex   Age  Survived
0         3    male  22.0         0
1         1  female  38.0         1
2         3  female  26.0         1
3         1  female  35.0         1
4         3    male  35.0         0
..      ...     ...   ...       ...
886       2    male  27.0         0
887       1  female  19.0         1
888       3  female   NaN         0
889       1    male  26.0         1
890       3    male  32.0         0

[891 rows x 4 columns]

In [16]:
# 널값 제거
titanic = titanic.dropna(axis=0)
titanic

Pclass     Sex   Age  Survived
0         3    male  22.0         0
1         1  female  38.0         1
2         3  female  26.0         1
3         1  female  35.0         1
4         3    male  35.0         0
..      ...     ...   ...       ...
885       3  female  39.0         0
886       2    male  27.0         0
887       1  female  19.0         1
889       1    male  26.0         1
890       3    male  32.0         0

[714 rows x 4 columns]

In [20]:
# 정수화
titanic.loc[:,"Sex"].replace(["female","male"],[0,1],inplace=True)
titanic

C:\Users\Administrator\AppData\Local\Temp\ipykernel_1920\469380419.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  titanic.loc[:,"Sex"].replace(["female","male"],[0,1],inplace=True)


Pclass  Sex   Age  Survived
0         3    1  22.0         0
1         1    0  38.0         1
2         3    0  26.0         1
3         1    0  35.0         1
4         3    1  35.0         0
..      ...  ...   ...       ...
885       3    0  39.0         0
886       2    1  27.0         0
887       1    0  19.0         1
889       1    1  26.0         1
890       3    1  32.0         0

[714 rows x 4 columns]

In [23]:
# 종속, 독립 변인 추출
titanic_input = titanic.loc[:,["Pclass", "Sex","Age"]]
titanic_target = titanic.loc[:,"Survived"]

print(titanic_input.count())
print(titanic_target.count())

Pclass    714
Sex       714
Age       714
dtype: int64
714


In [26]:
#넘파이로 변경
import numpy as np

tc_input_np = titanic_input.to_numpy()
tc_target_np = titanic_target.to_numpy()


array([0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,

In [27]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(
    tc_input_np, tc_target_np, random_state=42
)

In [29]:
# 로지스틱 회귀 (분류)
# 경사하강법, 시그모이드, 자연상수, 로그

from sklearn.linear_model import LogisticRegression # 결정트리를 사용하는 것이 더 좋다.
lr = LogisticRegression(C=1, max_iter=1000) # C값이 높으면 규제를 약하게, C값이 작으면 규제를 강하게
lr.fit(train_input,train_target)

LogisticRegression(C=1, max_iter=1000)

In [32]:
print(lr.score(train_input,train_target))
print(lr.score(test_input,test_target))

0.811214953271028
0.770949720670391


### 계수를 좋게 하려면?
- 규제와 에포크
- 데이터가 더 많이 필요 (행이 필요함)
- 칼럼을 더 많이 선정해야함. (요금, 몇명에서 같이 왔는지)
- 더 좋은 모델을 선택해야함.

In [36]:
# 황재민, 정재원, 김무진

lr.predict([[2,1,24]])

array([1], dtype=int64)

In [39]:
lr.predict([[1,0,24]])

array([1], dtype=int64)

In [40]:
lr.predict([[1,1,41]])

array([0], dtype=int64)

In [44]:
lr.predict([[1,1,37]])

array([0], dtype=int64)