# numpy 공부하기

In [5]:
import numpy as np

temp1 = [1,2,3,4]
arr1 = np.array(temp1, dtype=np.float16) # 이런식으로 해야 효율적으로 사용가능

print(type(temp1))
print(type(arr1))
print(temp1)
print(arr1) #,가 아닌 뒤에.이 붙음


<class 'list'>
<class 'numpy.ndarray'>
[1, 2, 3, 4]
[1. 2. 3. 4.]


In [6]:
print(type(arr1[0]))
print(type(temp1[0]))
print(arr1.shape) # 해당 데이터의 행렬을 출력 => 4행

<class 'numpy.float16'>
<class 'int'>
(4,)


```txt
3 -> 스칼라 Scala
[3,3,4,5] -> 1차원 벡터 Vector
[[1,2],[3,4]] -> 2차원 매트릭스 Matrix -> Pandas 라이브러리 사용예정 = R
3차원 -> 텐서 TenSor
2차원을 제외한 모든것은 numpy로 다루는것이 좋다!!
우선적으로 쿼리문을 사용해서 DB에 데이터를 필요한것만 가져와서 사용하는것이 가장 좋다!!
```

In [7]:
temp2 = [ 
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
]


In [8]:
arr2 = np.array(temp2, dtype=np.int8)
print(arr2)
print(arr2.shape) # 4행 3렬

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [9]:
temp3 = [
    [1,2,3,4],
    [5,6,7,8]
]

matrix1 = np.array(temp3)

print(matrix1.size)
print(matrix1.shape)
print("*"*50)

arr1 = matrix1.reshape(8,) # 1차원배열로 flattern => 뜻 = 평평하게하다 => Filter(끄집어내고)와 Map(담음) Vector
print(arr1)
arr2 = matrix1.reshape(4,2) # 4행 2열로 바꿈 => 사이즈가 맞아야 실행이됨 Matrix
print(arr2)
arr3 = matrix1.reshape(4,2,1) # 3차원으로 바꿈 Tensor
print(arr3)

8
(2, 4)
**************************************************
[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]


In [10]:
temp4 = [
    [1,2,3,4],
    [5,6,7,8]
]
matrix1 = np.array(temp4)
# matrix1[0][0]

print(matrix1[0,1]) # numpy에서만 사용가능 => ,로 인덱스 찾기가 가능
print(matrix1[:,1:3]) # 처음부터 할경우 시작번지 생략가능 # 시작번지는 1, 두번째 인수는 그 해당번지 직전(2번지)까지 출력

print(matrix1[1,2:]) # 끝까지 할경우 끝번지 생략가능
print(matrix1[1,-2]) # -를 붙일경우 뒤에서 부터 찾음

2
[[2 3]
 [6 7]]
[7 8]
7


In [11]:
temp1 = [
    [0, 1, 2, 3, 4],
    [5, 6, 7, 8, 9],
    [10, 11, 12, 13, 14]
]

m1 = np.array(temp1)

arr1 = m1.reshape(m1.size) # -를 쓰면 1차원 배열로 Flattern, 해당 배열의 사이즈를 사용해도 됨.
print(arr1)

arr2 = m1.flatten() # flatten 메서드 사용가능. => 값이 복제되는것 => 불변을 유지해주는 함수.
print(arr2)

print(m1[:,0::2]) # step => 첫 : = 모든행, 두번째 :2 = 2칸씩 띄워서

print(m1[::2,:])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]]


In [12]:
arr1 = np.arange(10) # 10개의 1차원 배열을 만들어줌
print(arr1)

arr2 = np.zeros(10)
print(arr2)

arr3 = np.ones(shape=(10,))
print(arr3)

arr4 = np.ones_like(arr3) # 똑같이 생긴 모양으로 값채우기 가능.
print(arr4)

[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
